---
conn_ssl:
  default: true
  description: Enable HTTPS (port 443) for connection
  required: true
  type: boolean
conn_timeout:
  default: 100
  description: Timeout for http requests
  required: true
  type: integer
conn_warn:
  default: false
  description: Disable valid SSL certificate warning on the connection
  required: true
  type: boolean
conn_verify:
  default: false
  description: Require valid SSL certificate on the connection
  required: true
  type: boolean
fortimanager:
  default:
  description: Fortimanager IP or hostname
  required: false
  type: string
password:
  default:
  description: User password for FortiManager remote-rpc call
  required: false
  secret: true
  type: string
username:
  default:
  description: User name for FortiManager remote-rpc call
  required: false
  type: string
