---
version: 2

jobs:
  build_and_test_python36:
    docker:
      - image: circleci/python:3.6
      - image: rabbitmq:3
      - image: mongo:3.4

    working_directory: ~/repo

    environment:
      VIRTUALENV_DIR: "~/virtualenv"
      # Don't install various StackStorm dependencies which are already
      # installed by CI again in the various check scripts
      ST2_INSTALL_DEPS: "0"

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-py36-{{ checksum "requirements.txt" }}
      - run:
          name: Download dependencies
          shell: /bin/bash
          command: |
            git clone -b master git://github.com/stackstorm-exchange/ci.git ~/ci
            ~/ci/.circle/dependencies
      - run:
          name: Run tests (Python 3.6)
          shell: /bin/bash
          command: ~/ci/.circle/test
      - save_cache:
          key: v1-dependency-cache-py36-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
            - ~/.apt-cache

  deploy:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    environment:
      VIRTUALENV_DIR: "~/virtualenv"

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-py36-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: /
      - run:
          name: Clone ci repo
          command: |
            [[ -d ~/ci ]] || git clone -b master git://github.com/stackstorm-exchange/ci.git ~/ci
            ~/ci/.circle/dependencies
      - run:
          name: Install apt dependencies
          command: |
            sudo apt-get update
            sudo apt -y install gmic optipng
      - run:
          name: Update exchange.stackstorm.org
          command: ~/ci/.circle/deployment

workflows:
  version: 2
  # Workflow which runs on each push
  build_test_deploy_on_push:
    jobs:
      - build_and_test_python36
      - deploy:
          requires:
            - build_and_test_python36
          filters:
            branches:
              only: master
  build_test_weekly:
    jobs:
      - build_and_test_python36
    # Workflow which runs nightly - note we don't perform deploy job on nightly
    # build
    triggers:
      # Run nightly build for the pack
      - schedule:
          # NOTE: We run it at 1 am UTC on every Saturday
          cron: "0 1 * * 6"
          filters:
            branches:
              only:
                - master
